package com.test.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-05-19T14:30:22.586+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "HelloService", 
                  wsdlLocation = "http://localhost:8888/framework/ws/helloService?wsdl",
                  targetNamespace = "http://server.test.com/") 
public class HelloService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.test.com/", "HelloService");
    public final static QName HelloWorldServerImpPort = new QName("http://server.test.com/", "HelloWorldServerImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8888/framework/ws/helloService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8888/framework/ws/helloService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IHelloWorldServer
     */
    @WebEndpoint(name = "HelloWorldServerImpPort")
    public IHelloWorldServer getHelloWorldServerImpPort() {
        return super.getPort(HelloWorldServerImpPort, IHelloWorldServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHelloWorldServer
     */
    @WebEndpoint(name = "HelloWorldServerImpPort")
    public IHelloWorldServer getHelloWorldServerImpPort(WebServiceFeature... features) {
        return super.getPort(HelloWorldServerImpPort, IHelloWorldServer.class, features);
    }

}
