package com.test.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-05-19T14:30:22.576+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://server.test.com/", name = "IHelloWorldServer")
@XmlSeeAlso({ObjectFactory.class})
public interface IHelloWorldServer {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findUsers", targetNamespace = "http://server.test.com/", className = "com.test.client.FindUsers")
    @WebMethod
    @ResponseWrapper(localName = "findUsersResponse", targetNamespace = "http://server.test.com/", className = "com.test.client.FindUsersResponse")
    public com.test.client.ListObject findUsers();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://server.test.com/", className = "com.test.client.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://server.test.com/", className = "com.test.client.SayHelloResponse")
    public java.lang.String sayHello(
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayUserName", targetNamespace = "http://server.test.com/", className = "com.test.client.SayUserName")
    @WebMethod
    @ResponseWrapper(localName = "sayUserNameResponse", targetNamespace = "http://server.test.com/", className = "com.test.client.SayUserNameResponse")
    public java.lang.String sayUserName(
        @WebParam(name = "user", targetNamespace = "")
        com.test.client.User user
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "say", targetNamespace = "http://server.test.com/", className = "com.test.client.Say")
    @WebMethod
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://server.test.com/", className = "com.test.client.SayResponse")
    public java.lang.String say(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
