
package com.test.message.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-05-20T16:23:19.450+08:00
 * Generated source version: 2.7.11
 * 
 */
public final class SDKClient_SDKService_Client {

    private static final QName SERVICE_NAME = new QName("http://sdkhttp.eucp.b2m.cn/", "SDKService");

    private SDKClient_SDKService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SDKService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SDKService ss = new SDKService(wsdlURL, SERVICE_NAME);
        SDKClient port = ss.getSDKService();  
        
        {
        System.out.println("Invoking chargeUp...");
        java.lang.String _chargeUp_arg0 = "";
        java.lang.String _chargeUp_arg1 = "";
        java.lang.String _chargeUp_arg2 = "";
        java.lang.String _chargeUp_arg3 = "";
        int _chargeUp__return = port.chargeUp(_chargeUp_arg0, _chargeUp_arg1, _chargeUp_arg2, _chargeUp_arg3);
        System.out.println("chargeUp.result=" + _chargeUp__return);


        }
        {
        System.out.println("Invoking getEachFee...");
        java.lang.String _getEachFee_arg0 = "";
        java.lang.String _getEachFee_arg1 = "";
        double _getEachFee__return = port.getEachFee(_getEachFee_arg0, _getEachFee_arg1);
        System.out.println("getEachFee.result=" + _getEachFee__return);


        }
        {
        System.out.println("Invoking cancelMOForward...");
        java.lang.String _cancelMOForward_arg0 = "";
        java.lang.String _cancelMOForward_arg1 = "";
        int _cancelMOForward__return = port.cancelMOForward(_cancelMOForward_arg0, _cancelMOForward_arg1);
        System.out.println("cancelMOForward.result=" + _cancelMOForward__return);


        }
        {
        System.out.println("Invoking setMOForward...");
        java.lang.String _setMOForward_arg0 = "";
        java.lang.String _setMOForward_arg1 = "";
        java.lang.String _setMOForward_arg2 = "";
        int _setMOForward__return = port.setMOForward(_setMOForward_arg0, _setMOForward_arg1, _setMOForward_arg2);
        System.out.println("setMOForward.result=" + _setMOForward__return);


        }
        {
        System.out.println("Invoking setMOForwardEx...");
        java.lang.String _setMOForwardEx_arg0 = "";
        java.lang.String _setMOForwardEx_arg1 = "";
        java.util.List<java.lang.String> _setMOForwardEx_arg2 = null;
        int _setMOForwardEx__return = port.setMOForwardEx(_setMOForwardEx_arg0, _setMOForwardEx_arg1, _setMOForwardEx_arg2);
        System.out.println("setMOForwardEx.result=" + _setMOForwardEx__return);


        }
        {
        System.out.println("Invoking sendVoice...");
        java.lang.String _sendVoice_arg0 = "";
        java.lang.String _sendVoice_arg1 = "";
        java.lang.String _sendVoice_arg2 = "";
        java.util.List<java.lang.String> _sendVoice_arg3 = null;
        java.lang.String _sendVoice_arg4 = "";
        java.lang.String _sendVoice_arg5 = "";
        java.lang.String _sendVoice_arg6 = "";
        int _sendVoice_arg7 = 0;
        long _sendVoice_arg8 = 0;
        java.lang.String _sendVoice__return = port.sendVoice(_sendVoice_arg0, _sendVoice_arg1, _sendVoice_arg2, _sendVoice_arg3, _sendVoice_arg4, _sendVoice_arg5, _sendVoice_arg6, _sendVoice_arg7, _sendVoice_arg8);
        System.out.println("sendVoice.result=" + _sendVoice__return);


        }
        {
        System.out.println("Invoking getMO...");
        java.lang.String _getMO_arg0 = "";
        java.lang.String _getMO_arg1 = "";
        java.util.List<com.test.message.client.Mo> _getMO__return = port.getMO(_getMO_arg0, _getMO_arg1);
        System.out.println("getMO.result=" + _getMO__return);


        }
        {
        System.out.println("Invoking getReport...");
        java.lang.String _getReport_arg0 = "";
        java.lang.String _getReport_arg1 = "";
        java.util.List<com.test.message.client.StatusReport> _getReport__return = port.getReport(_getReport_arg0, _getReport_arg1);
        System.out.println("getReport.result=" + _getReport__return);


        }
        {
        System.out.println("Invoking serialPwdUpd...");
        java.lang.String _serialPwdUpd_arg0 = "";
        java.lang.String _serialPwdUpd_arg1 = "";
        java.lang.String _serialPwdUpd_arg2 = "";
        java.lang.String _serialPwdUpd_arg3 = "";
        int _serialPwdUpd__return = port.serialPwdUpd(_serialPwdUpd_arg0, _serialPwdUpd_arg1, _serialPwdUpd_arg2, _serialPwdUpd_arg3);
        System.out.println("serialPwdUpd.result=" + _serialPwdUpd__return);


        }
        {
        System.out.println("Invoking registEx...");
        java.lang.String _registEx_arg0 = "";
        java.lang.String _registEx_arg1 = "";
        java.lang.String _registEx_arg2 = "";
        int _registEx__return = port.registEx(_registEx_arg0, _registEx_arg1, _registEx_arg2);
        System.out.println("registEx.result=" + _registEx__return);


        }
        {
        System.out.println("Invoking registDetailInfo...");
        java.lang.String _registDetailInfo_arg0 = "";
        java.lang.String _registDetailInfo_arg1 = "";
        java.lang.String _registDetailInfo_arg2 = "";
        java.lang.String _registDetailInfo_arg3 = "";
        java.lang.String _registDetailInfo_arg4 = "";
        java.lang.String _registDetailInfo_arg5 = "";
        java.lang.String _registDetailInfo_arg6 = "";
        java.lang.String _registDetailInfo_arg7 = "";
        java.lang.String _registDetailInfo_arg8 = "";
        java.lang.String _registDetailInfo_arg9 = "";
        int _registDetailInfo__return = port.registDetailInfo(_registDetailInfo_arg0, _registDetailInfo_arg1, _registDetailInfo_arg2, _registDetailInfo_arg3, _registDetailInfo_arg4, _registDetailInfo_arg5, _registDetailInfo_arg6, _registDetailInfo_arg7, _registDetailInfo_arg8, _registDetailInfo_arg9);
        System.out.println("registDetailInfo.result=" + _registDetailInfo__return);


        }
        {
        System.out.println("Invoking sendSMS...");
        java.lang.String _sendSMS_arg0 = "";
        java.lang.String _sendSMS_arg1 = "";
        java.lang.String _sendSMS_arg2 = "";
        java.util.List<java.lang.String> _sendSMS_arg3 = null;
        java.lang.String _sendSMS_arg4 = "";
        java.lang.String _sendSMS_arg5 = "";
        java.lang.String _sendSMS_arg6 = "";
        int _sendSMS_arg7 = 0;
        long _sendSMS_arg8 = 0;
        int _sendSMS__return = port.sendSMS(_sendSMS_arg0, _sendSMS_arg1, _sendSMS_arg2, _sendSMS_arg3, _sendSMS_arg4, _sendSMS_arg5, _sendSMS_arg6, _sendSMS_arg7, _sendSMS_arg8);
        System.out.println("sendSMS.result=" + _sendSMS__return);


        }
        {
        System.out.println("Invoking getBalance...");
        java.lang.String _getBalance_arg0 = "";
        java.lang.String _getBalance_arg1 = "";
        double _getBalance__return = port.getBalance(_getBalance_arg0, _getBalance_arg1);
        System.out.println("getBalance.result=" + _getBalance__return);


        }
        {
        System.out.println("Invoking logout...");
        java.lang.String _logout_arg0 = "";
        java.lang.String _logout_arg1 = "";
        int _logout__return = port.logout(_logout_arg0, _logout_arg1);
        System.out.println("logout.result=" + _logout__return);


        }
        {
        System.out.println("Invoking getVersion...");
        java.lang.String _getVersion__return = port.getVersion();
        System.out.println("getVersion.result=" + _getVersion__return);


        }

        System.exit(0);
    }

}
