package com.test.message.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-05-20T16:23:19.525+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://sdkhttp.eucp.b2m.cn/", name = "SDKClient")
@XmlSeeAlso({ObjectFactory.class})
public interface SDKClient {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "chargeUp", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.ChargeUp")
    @WebMethod
    @ResponseWrapper(localName = "chargeUpResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.ChargeUpResponse")
    public int chargeUp(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getEachFee", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.GetEachFee")
    @WebMethod
    @ResponseWrapper(localName = "getEachFeeResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.GetEachFeeResponse")
    public double getEachFee(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cancelMOForward", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.CancelMOForward")
    @WebMethod
    @ResponseWrapper(localName = "cancelMOForwardResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.CancelMOForwardResponse")
    public int cancelMOForward(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setMOForward", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.SetMOForward")
    @WebMethod
    @ResponseWrapper(localName = "setMOForwardResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.SetMOForwardResponse")
    public int setMOForward(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setMOForwardEx", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.SetMOForwardEx")
    @WebMethod
    @ResponseWrapper(localName = "setMOForwardExResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.SetMOForwardExResponse")
    public int setMOForwardEx(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.util.List<java.lang.String> arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendVoice", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.SendVoice")
    @WebMethod
    @ResponseWrapper(localName = "sendVoiceResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.SendVoiceResponse")
    public java.lang.String sendVoice(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.util.List<java.lang.String> arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        int arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        long arg8
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMO", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.GetMO")
    @WebMethod
    @ResponseWrapper(localName = "getMOResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.GetMOResponse")
    public java.util.List<com.test.message.client.Mo> getMO(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getReport", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.GetReport")
    @WebMethod
    @ResponseWrapper(localName = "getReportResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.GetReportResponse")
    public java.util.List<com.test.message.client.StatusReport> getReport(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "serialPwdUpd", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.SerialPwdUpd")
    @WebMethod
    @ResponseWrapper(localName = "serialPwdUpdResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.SerialPwdUpdResponse")
    public int serialPwdUpd(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registEx", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.RegistEx")
    @WebMethod
    @ResponseWrapper(localName = "registExResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.RegistExResponse")
    public int registEx(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registDetailInfo", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.RegistDetailInfo")
    @WebMethod
    @ResponseWrapper(localName = "registDetailInfoResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.RegistDetailInfoResponse")
    public int registDetailInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        java.lang.String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        java.lang.String arg9
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendSMS", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.SendSMS")
    @WebMethod
    @ResponseWrapper(localName = "sendSMSResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.SendSMSResponse")
    public int sendSMS(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.util.List<java.lang.String> arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        int arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        long arg8
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBalance", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.GetBalance")
    @WebMethod
    @ResponseWrapper(localName = "getBalanceResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.GetBalanceResponse")
    public double getBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "logout", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.Logout")
    @WebMethod
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.LogoutResponse")
    public int logout(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.GetVersion")
    @WebMethod
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "com.test.message.client.GetVersionResponse")
    public java.lang.String getVersion();
}
